### Execute: ansible-playbook ash3d_Redhat.yml -K
# This is tested with CentOS 8/9, Rocky 8/9, RHEL 8/9
#
## Make sure user 'ash3d' is on the sudo list
#
## Update system
# sudo dnf config-manager --set-enabled crb
# sudo yum update
#
## Add whatever certificate your network needs
#
# sudo yum install ansible
#
# Re-runs will do very little. If needing to force reloads of all content 
# delete these directories/files on the target server: 
# If you are pushing to remote hosts, update your local hosts file and make suer
# the server tag is changed below.
# hosts are listed in /etc/ansible/hosts
---

- name: Install Ash3d and web scripts
  #hosts: ash3dservers
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

    - name: Create bin directory
      file:
        path: /home/ash3d/bin
        state: directory
    - name: Create Programs/GIT directory
      file:
        path: /home/ash3d/Programs/GIT
        state: directory
        recurse: yes
        mode: 0775
        owner: ash3d
        group: ash3d

    ############################################################################
    ### Ash3d                                                                ###
    ############################################################################

    # sudo dnf config-manager --set-enabled crb

    - name: Enable epel
      yum:
        name: epel-release
        state: latest

    # git is needed to pull the software
    # gcc-fortran is needed to build the software, with gcc and gcc-c++ needed for pre-processing
    # make controls the build
    # lapack and blas are needed for the diffusion solver. Only lapack and lapack-devel are normally
    #  needed, but some distros have slightly different names so will install the glob
    - name: Install build distribution software
      yum:
        name: git, gcc, gcc-gfortran, gcc-c++, make, lapack*, blas*
        state: latest

    # netcdf is needed to read windfiles and write output. eccodes is needed to read grib files
    - name: Install netcdf and eccodes distribution software
      yum:
        name: netcdf, netcdf-devel, netcdf-fortran, netcdf-fortran-devel, eccodes, eccodes-devel
        state: latest

    # bc is a desk calculator used in post-processing scripts
    # zip is needed for bundeling output and converting kml to kmz files
    # perl is used in some post-processing scripts
    # nco is a netcdf manipulation package used in post-processing (mainly ncks)
    # GMT is the primary mapping package used in post-processing scripts (also in Ash3d_Post_Proc)
    # unix2dos is used in post-processing to strip control characters from text files
    # ImageMagick is used to assemble final images with legends/disclaimers/banners.
    # gifsicle produces animated gifs
    # ghostscript is used to convert ps,eps,pdf files
    # java is needed run the script the uses netcdf-java to convert grib to netcdf files
    - name: Install postproc distribution software for maps
      yum:
        name: bc, zip, perl, nco, GMT, GMT-common, gshhg-gmt*, unix2dos, ImageMagick, gifsicle, ghostscript, java
        state: latest

    # proj is needed to run the test cases (make check) for volcano-ash3d-projection
    # plplot is used for producing png images with Ash3d_Post_Proc
    # gnuplot is used for the accumulation plots at airports and for Ash3d_Post_Proc
    # octave is only used by volcano-ash3d-optionalmodules for convergence testing
    - name: Install software needed for Ash3d_PostProc
      yum:
        name: proj, plplot, plplot-devel, plplot-fortran-devel, gnuplot, octave
        state: latest

#       CentOS7 uses package gdal-python, but 8/9 use gdal-python-tools
#       Note that gdal tool are only needed if you plan to use GFSVolc_to_gif_tvar.sh for dp dp_mm
#       or GFSVolc_to_gif_dp[_mm].sh which uses xyz2shp.py to generate the shapefiles. If you use
#       PP_Ash3d_to_gif.sh, then shapefiles are written directly from Ash3d_Post_proc
#    - name: Install postproc distribution software for shapefiles (used by python script)
#      yum:
#        name: gdal, gdal-devel, gdal-pyth*
#        state: latest

    # git clone https://code.usgs.gov/vsc/ash3d/volcano-ash3d-hourssince.git
    - name: Clone volcano-ash3d-hourssince git repository.
      git:
        #repo: 'https://github.com/DOI-USGS/volcano-ash3d-hourssince.git'
        repo: 'https://code.usgs.gov/vsc/ash3d/volcano-ash3d-hourssince.git'
        dest: /home/ash3d/Programs/GIT/volcano-ash3d-hourssince
        accept_hostkey: yes
        force: yes
      become_user: ash3d
    - name: Building libhourssince
      command: 'make all chdir=/home/ash3d/Programs/GIT/volcano-ash3d-hourssince/'
    - name: Installing libhourssince
      command: 'make install chdir=/home/ash3d/Programs/GIT/volcano-ash3d-hourssince/'

    # git clone https://code.usgs.gov/vsc/ash3d/volcano-ash3d-projection.git
    - name: Clone volcano-ash3d-projection git repository.
      git:
        #repo: 'https://github.com/DOI-USGS/volcano-ash3d-projection.git'
        repo: 'https://code.usgs.gov/vsc/ash3d/volcano-ash3d-projection.git'
        dest: /home/ash3d/Programs/GIT/volcano-ash3d-projection
        accept_hostkey: yes
        force: yes
      become_user: ash3d
    - name: Building libprojection
      command: 'make all chdir=/home/ash3d/Programs/GIT/volcano-ash3d-projection/'
    - name: Installing libprojection
      command: 'make install chdir=/home/ash3d/Programs/GIT/volcano-ash3d-projection/'

    # git clone https://code.usgs.gov/vsc/ash3d/volcano-ash3d-metreader.git
    - name: Clone volcano-ash3d-metreader git repository.
      git:
        #repo: 'https://github.com/DOI-USGS/volcano-ash3d-metreader.git'
        repo: 'https://code.usgs.gov/vsc/ash3d/volcano-ash3d-metreader.git'
        dest: /home/ash3d/Programs/GIT/volcano-ash3d-metreader
        accept_hostkey: yes
        force: yes
      become_user: ash3d
    - name: Building libmetreader
      command: 'make all chdir=/home/ash3d/Programs/GIT/volcano-ash3d-metreader/'
    - name: Installing libmetreader
      command: 'make install chdir=/home/ash3d/Programs/GIT/volcano-ash3d-metreader/'
    - name: Create bin directory
      file:
        path: /home/ash3d/bin
        state: directory
      become_user: ash3d
    - name: Create ncj directory
      file:
        path: /home/ash3d/ncj
        state: directory
      become_user: ash3d
    - name: Download netcdf-java
      get_url: url=http://downloads.unidata.ucar.edu/netcdf-java/5.4.2/netcdfAll-5.4.2.jar dest=/home/ash3d/ncj/
      become_user: ash3d
    - name: Create cron_logs directory
      file:
        path: /home/ash3d/cron_logs
        state: directory
      become_user: ash3d
    - name: Create directory for NCEP data
      file:
        path: /data/WindFiles/NCEP/dbuffer
        state: directory
        recurse: yes
        mode: 0775
        owner: ash3d
        group: ash3d
    - name: Install NCEP download scripts to crontab
      cron:
        name: "Download NCEP"
        user: ash3d
        hour: '01'
        minute: '01'
        weekday: '06'
        job: /opt/USGS/bin/autorun_scripts/autorun_NCEP_50YearReanalysis.sh   > /home/ash3d/cron_logs/NCEP_50yr_log   2>&1
      become_user: ash3d
    - name: Create directory for gfs data
      file:
        path: /data/WindFiles/gfs
        state: directory
        recurse: yes
        mode: 0775
        owner: ash3d
        group: ash3d
    - name: Install GFS 00 download scripts to crontab
      cron:
        name: "Download GFS 00"
        user: ash3d
        hour: '06'
        minute: '01'
        job: /opt/USGS/bin/autorun_scripts/autorun_gfs.sh 0p50 0             > /home/ash3d/cron_logs/gfs00_log      2>&1
    - name: Install GFS 12 download scripts to crontab
      cron:
        name: "Download GFS 12"
        user: ash3d
        hour: '19'
        minute: '01'
        job: /opt/USGS/bin/autorun_scripts/autorun_gfs.sh 0p50 12             > /home/ash3d/cron_logs/gfs12_log      2>&1

    - name: Install prune script
      cron:
        name: "Prune old windfiles"
        user: ash3d
        hour: '03'
        minute: '30'
        job: /opt/USGS/bin/autorun_scripts/prune_windfiles.sh                 > /home/ash3d/cron_logs/prune.log       2>&1
########################
#  Before building Ash3d_PostProc, it is useful to have dislin installed
#  which can be used to generate both maps and contours for shapefiles.
#######DISLIN
#mkdir ~/Programs
#cd ~/Programs
#mkdir Tarballs
#wget https://www.dislin.de/downloads/linux/i586_64/dislin-11.5.linux.i586_64.tar.gz
#yum install openmotif-devel
#Add to .bash_profile:
#/home/ash3d/.bash_profile
# DISLIN=/usr/local/dislin
# export DISLIN
# PATH=${PATH}:${DISLIN}/bin
# export PATH
# LD_LIBRARY_PATH=$DISLIN:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH
#cd /home/ash3d/Programs/Tarballs/dislin-11.5/linux_i586_64/gf
#gfortran -c ../dislin.f90
#  or
#gfortran -c ../dislin_d.f90
#  if you want the double-precision library; You need to have DS in Ash3d_PostProc_dislin.f90
#  match the choice here.
#cd /home/ash3d/Programs/Tarballs/dislin-11.5
#./INSTALL
###############################
#
#    git clone https://code.usgs.gov/vsc/ash3d/volcano-ash3d.git
    - name: Clone volcano-ash3d git repository
      git:
        #repo: 'https://github.com/DOI-USGS/volcano-ash3d.git'
        repo: 'https://code.usgs.gov/vsc/ash3d/volcano-ash3d.git'
        dest: /home/ash3d/Programs/GIT/volcano-ash3d
        accept_hostkey: yes
        force: yes
        become_user: ash3d
    - name: Building Ash3d
      command: 'make all chdir=/home/ash3d/Programs/GIT/volcano-ash3d/src/'
    - name: Building Ash3d_PostProc
      command: 'make postproc chdir=/home/ash3d/Programs/GIT/volcano-ash3d/src/'
    - name: Installing Ash3d
      command: 'make install chdir=/home/ash3d/Programs/GIT/volcano-ash3d/src/'

#    git clone https://code.usgs.gov/vsc/ash3d/volcano-ash3d-web.git
    - name: Clone volcano-ash3d-web git repository.
      git:
        #repo: 'https://github.com/DOI-USGS/volcano-ash3d-web.git'
        repo: 'https://code.usgs.gov/vsc/ash3d/volcano-ash3d-web.git'
        dest: /home/ash3d/Programs/GIT/volcano-ash3d-web
        accept_hostkey: yes
        force: yes
      become_user: ash3d
    - name: Building Ash3d_web-master
      command: 'make all chdir=/home/ash3d/Programs/GIT/volcano-ash3d-web/src/'
    - name: Installing Ash3d_web
      command: 'make install chdir=/home/ash3d/Programs/GIT/volcano-ash3d-web/src/'

    ########
