      program legend_placer_dp

!     Program determines the coordinates of legends on maps generated by 
!     GFSVolc_to_gif_dp.sh and GFSVolc_to_gif_dp_mm.sh
!     This is essentially very similar to legend_placer_ac, but this program
!     also takes into consideration the location of the deposit from a GMT contour file.
!     This program requires the file map_range.txt to exist as generated
!     from the above script with this command:
!       echo "$LLLON $URLON $LLLAT $URLAT $VCLON $VCLAT" > map_range.txt
!     Also expects contour files

      implicit none

      real(kind=8) :: caveats_height, dlat, dlon
      real(kind=8) :: latmax, latmax_rad, latmin, latmin_rad
      real(kind=8) :: lat_now, lon_now
      real(kind=8) :: legend1x_position, legend1y_position
      real(kind=8) :: legend1x_LR_prim, legend1x_UL_prim
      real(kind=8) :: legend1y_LR_prim, legend1y_UL_prim
      real(kind=8) :: legend1x_LL_alt1, legend1x_UL_alt1
      real(kind=8) :: legend1y_LL_alt1, legend1y_UL_alt1
      real(kind=8) :: legend1_height, legend1_width
      real(kind=8) :: legend2x_position, legend2y_position
      real(kind=8) :: legend2x_UL_prim, legend2x_UR_prim
      real(kind=8) :: legend2y_UL_prim, legend2y_UR_prim
      real(kind=8) :: legend2x_LL_alt1, legend2x_UL_alt1, legend2x_UR_alt1
      real(kind=8) :: legend2y_LL_alt1, legend2y_UL_alt1, legend2y_UR_alt1
      real(kind=8) :: legend2x_LL_alt2, legend2x_UL_alt2
      real(kind=8) :: legend2y_LL_alt2, legend2y_UL_alt2
      real(kind=8) :: legend2_height, legend2_width
      real(kind=8) :: lonmax, lonmax_rad, lonmin, lonmin_rad
      real(kind=8) :: map_height, map_width
      real(kind=8) :: pi
      real(kind=8) :: xLL,xLR,xUL,    xleft_map,xright_map
      real(kind=8) :: yLL,yLR,yUL,yUR,ybottom_map,ytop_map
      real(kind=8) :: vclat, vclon
      real(kind=8) :: lat_to_pixels, pixels_to_lat
      integer  :: Iostatus =1
      integer  :: legend2x_pixels, legend2y_pixels
      logical  :: legend1_prim_overlaps_contour, legend1_alt1_overlaps_contour
      logical  :: legend2_prim_overlaps_contour, legend2_alt1_overlaps_contour, legend2_alt2_overlaps_contour
      logical  :: legend1_prim_overlaps_volcano, legend1_alt1_overlaps_volcano
      logical  :: legend2_prim_overlaps_volcano, legend2_alt1_overlaps_volcano, legend2_alt2_overlaps_volcano
      logical  :: wrap_lon
      character(len=80) :: inputline
      character(len=1)  :: test_char
      logical           :: IsThere

      character(len=23) :: cfile1, cfile2, cfile3, cfile4
      character(len=19) :: progname
      character(len=23) :: outfile

      !set constants
      pi             = 3.14159_8
      cfile1 = 'contourfile_0.1_0_i.xyz'
      cfile2 = 'contourfile_0.1_0.xyz'
      cfile3 = 'contourfile_0.1_1_i.xyz'
      cfile4 = 'contourfile_0.1_2_i.xyz'
      progname = 'legend_positions_dp'
      outfile = progname // '.txt'

      !set dimensions of map and legends.  All dimensions are in pixels unless specified
      map_width       = 20.0_8*72.0_8/2.54_8 !width of map, pixels
      legend1_width   = 219.0_8              !width of legend containin ESP's
      legend1_height  = 96.0_8
      legend2_width   = 125.0_8              !width of legend_dep_nws.gif
      legend2_height  = 222.0_8
      xleft_map       = 31.0_8               !x offset of left side of map
      xright_map      = 631.0_8-598.0_8      !x offset of right side of map from right side of image
      ybottom_map     = 545.0_8-462.0_8      !y offset of base of map from base of image
      ytop_map        = -120.0_8             !y offset of top of map from top of image
      caveats_height  = 91.0_8

      !set overlap booleans
      legend1_prim_overlaps_contour = .false.       !=.true. if legend1 covers contours
      legend1_alt1_overlaps_contour = .false.       !=.true. if legend1 in alt. position covers contours
      legend2_prim_overlaps_contour = .false.       !=.true. if legend2 covers contours
      legend2_alt1_overlaps_contour = .false.       !=.true. if legend2 in alt. position covers contours
      legend2_alt2_overlaps_contour = .false.       !=.true. if legend2 in alt. position covers contours
      legend1_prim_overlaps_volcano = .false.       !=.true. if legend1 covers contours
      legend1_alt1_overlaps_volcano = .false.       !=.true. if legend1 in alt. position covers contours
      legend2_prim_overlaps_volcano = .false.       !=.true. if legend2 covers contours
      legend2_alt1_overlaps_volcano = .false.       !=.true. if legend2 in alt. position covers contours
      legend2_alt2_overlaps_volcano = .false.       !=.true. if legend2 in alt. position covers contours
      wrap_lon                      = .false.       !=.true. if longitude wraps across the antimeridian

      !open map_range.txt and read range of latitute, longitude
      inquire( file='map_range.txt', exist=IsThere )
      if(.not.IsThere)then
        write(6,*)'ERROR: ',trim(adjustl(progname)),' cannot find map_range.txt'
        stop 1
      endif
      open(unit=10,file='map_range.txt')
      read(10,*,err=3001) lonmin, lonmax, latmin, latmax, vclon, vclat
      close(10)
      lonmin_rad = lonmin*pi/180.0_8
      lonmax_rad = lonmax*pi/180.0_8
      latmin_rad = latmin*pi/180.0_8
      latmax_rad = latmax*pi/180.0_8
      dlon       = lonmax-lonmin
      if (dlon.lt.0.0_8) then
        dlon     = dlon+360.0_8
        wrap_lon = .true.
      endif
      dlat       = latmax-latmin

      !adjust offsets depending on latitude (some labels are wider than others)
      if (latmin.lt.-10.0_8) then
        xleft_map  = 40.0_8
        xright_map = 41.0_8
      endif

      !calculate map scale, km per cm at the latitude of the volcano
      map_height = ((map_width*180.0_8)/(pi*dlon)) * &
                     log(tan(pi/4.0_8+latmax_rad/2.0_8)/ &
                         tan(pi/4.0_8+latmin_rad/2.0_8))
      write(6,6) int(map_width), int(map_height), &
                 int(map_width+xleft_map+xright_map), int(map_height+ytop_map+ybottom_map)
6     format('    Estimated map and figure dimensions (pixels)',/, &
             '             width   height',/, &
             '    map      ',i4,i8,/, &
             '    figure   ',i4,i8)

!***************************************************************************************************************
      !FIND POSITIONS FOR LEGENDS

      !Positiions for legends
      !---------------------------------------------------------!
      ! legend1                       legend1_alt1, legend2_alt1!
      !                                                         !
      !                                                         !
      !                                                         !
      ! legend2                                    legend2_alt2 !
      !                                                         !
      !                                                         !
      !                                                         !
      !                                                         !
      !                                              USGS_vid   !
      !---------------------------------------------------------!

      !calculate upper left, lower right corners of ESP legend
      !NOTE: THESE COORDINATES ARE IN LATITUDE/LONGITUDE
      legend1x_UL_prim = lonmin+0.02_8*dlon                                            !find UL in lat, lon
      legend1y_UL_prim = latmin+0.98_8*dlat
      xUL              = xleft_map+dlon*(0.02_8+legend1_width/map_width)                 !convert to x, y
      yUL              = lat_to_pixels(ytop_map,map_height,latmin,latmax,legend1y_UL_prim)
      xLR              = xUL + legend1_width                                         !find LR in x, y
      yLR              = yUL + legend1_height
      legend1x_LR_prim = legend1x_UL_prim + dlon*(legend1_width/map_width)
      legend1y_LR_prim = pixels_to_lat(ytop_map,map_height,latmin,latmax,yLR)

      !calculate upper right, lower left corners of ESP legend (alternate placement)
      xLL              = xleft_map+0.98_8*map_width-legend1_width
      legend1x_LL_alt1 = lonmin+dlon*((xLL-xleft_map)/map_width)
      legend1y_LL_alt1 = legend1y_LR_prim
      legend1x_UL_alt1 = legend1x_LL_alt1
      legend1y_UL_alt1 = legend1y_UL_prim

      !calculate corners of contour legend
      yUR              = ytop_map+0.98_8*map_height - legend2_height
      legend2x_UR_prim = lonmin+dlon*(0.02_8+legend2_width/map_width)
      legend2y_UR_prim = pixels_to_lat(ytop_map,map_height,latmin,latmax,yUR)
      legend2x_UL_prim = legend1x_UL_prim
      legend2y_UL_prim = legend2y_UR_prim

      !calculate corners of contour legend, alternate position
      legend2x_UR_alt1 = lonmin+0.98_8*dlon                                       !find UR in lat, lon
      legend2y_UR_alt1 = legend1y_UL_prim
      legend2x_LL_alt1 = lonmax-dlon*(0.02_8+legend2_width/map_width)              !find LL in lon
      yLL              = ytop_map+0.02_8*map_height+legend2_height
      legend2y_LL_alt1 = pixels_to_lat(ytop_map,map_height,latmin,latmax,yLL)         !convert yLL to LL in lat
      legend2x_UL_alt1 = legend2x_LL_alt1
      legend2y_UL_alt1 = legend2y_UR_alt1

      !Corners of the contour legends, alternate position #2
      legend2x_UL_alt2 = legend2x_LL_alt1                                        !find UL in lat, lon
      legend2y_UL_alt2 = legend1y_LL_alt1-0.02_8*dlat
      legend2x_LL_alt2 = legend2x_LL_alt1                                        !find LL in lon
      yLL = lat_to_pixels(ytop_map,map_height,latmin,latmax,legend2y_UL_alt2) &      !find LL in y
             + legend2_height
      legend2y_LL_alt2 = pixels_to_lat(ytop_map,map_height,latmin,latmax,yLL)        !convert to lat

!**************************************************************************************************************

      !READ FILES WITH CONTOUR LINES

      !Open first file
      !there are at least three possible names for this file, so we have
      !to try all of them
      write(6,*) 'trying to open ',cfile1
      open(unit=12,file=cfile1,status='old',err=200)  !file name if it's a closed contour
      write(6,*) '   opening ',cfile1
      goto 240
200   write(6,*) 'Could not find ',cfile1

      write(6,*) 'trying to open ',cfile2
      open(unit=12,file=cfile2,status='old',err=250)    !file name if it's not
      write(6,*) '   opening ',cfile2

240   read(12,'(a80)',IOSTAT=Iostatus) inputline
      do while (Iostatus.ge.0)
        !Read in latitude & longitude
        !read(12,'(a80)',IOSTAT=Iostatus) inputline
        read(inputline,'(a1)') test_char
        if(test_char.eq.'>')then
          read(12,'(a80)',IOSTAT=Iostatus) inputline
        endif
        read(inputline,*,err=3010) lon_now, lat_now
        !Adjust longitude if the region crosses the antimeridian
        !if ((wrap_lon.eqv..true.).and.(lon_now.lt.0.)) lon_now=lon_now+360.
        if ((lonmax.gt.180.0_8).and.(lon_now.lt.0.0_8)) lon_now=lon_now+360.0_8
        !See whether any of the legend positions overlap these points
        if  ((lon_now<legend1x_LR_prim).and.(lat_now>legend1y_LR_prim)) legend1_prim_overlaps_contour =.true.
        if  ((lon_now>legend1x_LL_alt1).and.(lat_now>legend1y_LL_alt1)) legend1_alt1_overlaps_contour =.true.
        if  ((lon_now<legend2x_UR_prim).and.(lat_now<legend2y_UR_prim)) legend2_prim_overlaps_contour =.true.
        if  ((lon_now>legend2x_LL_alt1).and.(lat_now>legend2y_LL_alt1)) legend2_alt1_overlaps_contour =.true.
        if (((lon_now>legend2x_UL_alt2).and.(lat_now<legend2y_UL_alt2)).and. &
            ((lon_now>legend2x_LL_alt2).and.(lat_now>legend2y_LL_alt2)))legend2_alt2_overlaps_contour=.true.
        read(12,'(a80)',IOSTAT=Iostatus) inputline
      enddo
      close(12)

      !See if there are other files of isolated contours
      Iostatus = 1
      write(6,*) '   Looking for ',cfile3
      open(unit=13,file=cfile3,status='old',err=350)
      write(6,*) '   found ',cfile3
      do while (Iostatus.ge.0)
        !Read in latitude & longitude
        read(13,'(a80)',IOSTAT=Iostatus) inputline
        read(inputline,'(a1)') test_char
        if(test_char.eq.'>')then
          read(13,'(a80)',IOSTAT=Iostatus) inputline
        endif
        read(inputline,*,err=3015) lon_now, lat_now
        !Adjust for regions that cross the antimeridian
        !if ((wrap_lon.eqv..true.).and.(lon_now.lt.0.)) lon_now=lon_now+360.
        if ((lonmax.gt.180.0_8).and.(lon_now.lt.0.0_8)) lon_now=lon_now+360.0_8
        !See whether any of the legend positions overlap these points
        if  ((lon_now<legend1x_LR_prim).and.(lat_now>legend1y_LR_prim)) legend1_prim_overlaps_contour =.true.
        if  ((lon_now>legend1x_LL_alt1).and.(lat_now>legend1y_LL_alt1)) legend1_alt1_overlaps_contour =.true.
        if  ((lon_now<legend2x_UR_prim).and.(lat_now<legend2y_UR_prim)) legend2_prim_overlaps_contour =.true.
        if  ((lon_now>legend2x_LL_alt1).and.(lat_now>legend2y_LL_alt1)) legend2_alt1_overlaps_contour =.true.
        if (((lon_now>legend2x_UL_alt2).and.(lat_now<legend2y_UL_alt2)).and. &
            ((lon_now>legend2x_LL_alt2).and.(lat_now>legend2y_LL_alt2)))legend2_alt2_overlaps_contour =.true.
      enddo
      close(13)

      Iostatus = 1
      write(6,*) '   Looking for ',cfile4
      open(unit=14,file=cfile4,status='old',err=350)
      write(6,*) '   found ',cfile4
      do while (Iostatus.ge.0)
        !Read in latitude & longitude
        read(14,'(a80)',IOSTAT=Iostatus) inputline
        read(inputline,'(a1)') test_char
        if(test_char.eq.'>')then
          read(14,'(a80)',IOSTAT=Iostatus) inputline
        endif
        read(inputline,*,err=3020) lon_now, lat_now
        !Adjust for regions that cross the antimeridian
        !if ((wrap_lon.eqv..true.).and.(lon_now.lt.0.)) lon_now=lon_now+360.
        if ((lonmax.gt.180.0_8).and.(lon_now.lt.0.0_8)) lon_now=lon_now+360.0_8
        !See whether any of the legend positions overlap these points
        if  ((lon_now<legend1x_LR_prim).and.(lat_now>legend1y_LR_prim)) legend1_prim_overlaps_contour =.true.
        if  ((lon_now>legend1x_LL_alt1).and.(lat_now>legend1y_LL_alt1)) legend1_alt1_overlaps_contour =.true.
        if  ((lon_now<legend2x_UR_prim).and.(lat_now<legend2y_UR_prim)) legend2_prim_overlaps_contour =.true.
        if  ((lon_now>legend2x_LL_alt1).and.(lat_now>legend2y_LL_alt1)) legend2_alt1_overlaps_contour =.true.
        if (((lon_now>legend2x_UL_alt2).and.(lat_now<legend2y_UL_alt2)).and. &
            ((lon_now>legend2x_LL_alt2).and.(lat_now>legend2y_LL_alt2)))legend2_alt2_overlaps_contour =.true.
      enddo
      close(14)

350   continue

!*******************************************************************************************************

      !See if the volcano overlaps any of these legend locations
      if  ((vclon<legend1x_LR_prim).and.(vclat>legend1y_LR_prim)) legend1_prim_overlaps_volcano=.true.
      if  ((vclon>legend1x_LL_alt1).and.(vclat>legend1y_LL_alt1)) legend1_alt1_overlaps_volcano=.true.
      if  ((vclon<legend2x_UR_prim).and.(vclat<legend2y_UR_prim)) legend2_prim_overlaps_volcano=.true.
      if  ((vclon>legend2x_LL_alt1).and.(vclat>legend2y_LL_alt1)) legend2_alt1_overlaps_volcano=.true.
      if (((vclon>legend2x_UL_alt2).and.(vclat<legend2y_UL_alt2)).and. &
          ((vclon>legend2x_LL_alt2).and.(vclat>legend2y_LL_alt2)))legend2_alt2_overlaps_volcano=.true.

      write(6,*) 'vclon=',vclon,', vclat=',vclat
      write(6,*) 'legend2x_LL_alt=',legend2x_LL_alt1,', legend2y_LL_alt=',legend2y_LL_alt1
      write(6,*) 'legend1_prim_overlaps_contour = ',legend1_prim_overlaps_contour
      write(6,*) 'legend1_prim_overlaps_volcano = ',legend1_prim_overlaps_volcano
      write(6,*) 'legend1_alt1_overlaps_volcano = ',legend1_alt1_overlaps_volcano
      write(6,*) 'legend1_alt1_overlaps_contour = ',legend1_alt1_overlaps_contour
      write(6,*) 'legend2_prim_overlaps_volcano = ',legend2_prim_overlaps_volcano
      write(6,*) 'legend2_prim_overlaps_contour = ',legend2_prim_overlaps_contour
      write(6,*) 'legend2_alt1_overlaps_volcano = ',legend2_alt1_overlaps_volcano
      write(6,*) 'legend2_alt1_overlaps_contour = ',legend2_alt1_overlaps_contour
      write(6,*) 'legend2_alt2_overlaps_volcano = ',legend2_alt2_overlaps_volcano
      write(6,*) 'legend2_alt2_overlaps_contour = ',legend2_alt2_overlaps_contour

      !ADJUST LOCATION OF LEGENDS DEPENDING ON OVERLAPS

      !set default positions
      legend1x_position = legend1x_UL_prim
      legend1y_position = legend1y_UL_prim
      legend2x_position = legend2x_UL_prim
      legend2y_position = legend2y_UL_prim

      if (legend1_prim_overlaps_contour) then
        if (legend2_prim_overlaps_contour) then
          if (legend1_alt1_overlaps_volcano.eqv..false.) then    !Move legend1 only if it doesn't cover volcano
            legend1x_position = legend1x_UL_alt1
            legend1y_position = legend1y_UL_alt1
          endif
          if (legend2_alt2_overlaps_volcano.eqv..false.) then    !Move legend2 only if it doesn't cover volcano
            legend2x_position = legend2x_UL_alt2
            legend2y_position = legend2y_UL_alt2
          endif
        else
          if (legend1_alt1_overlaps_volcano.eqv..false.) then    !Move legend1 only if it doesn't cover volcano
            legend1x_position = legend1x_UL_alt1
            legend1y_position = legend1y_UL_alt1
          endif
        endif
      else
        if (legend2_prim_overlaps_contour) then
          if (legend2_alt1_overlaps_volcano.eqv..false.) then    !Move legend2 only if it doesn't cover volcano
            legend2x_position = legend2x_UL_alt1
            legend2y_position = legend2y_UL_alt1
          endif
        endif
      endif

      !convert legend2 position from lat/lon to pixels
      legend2x_pixels = floor(xleft_map+map_width*(legend2x_position-lonmin)/dlon)
      legend2y_pixels = floor(lat_to_pixels(ytop_map,map_height,latmin,latmax,legend2y_position))
      legend2y_pixels = max(0,legend2y_pixels)

      write(6,3) legend1x_position, legend1y_position, legend2x_position, legend2y_position, &
                                                       legend2x_pixels,   legend2y_pixels,   &
                 outfile
3     format('    Caption placement:   lon       lat     x     y',/, &
             '    ESP legend    ',2f10.3,/, &
             '    Contour legend',2f10.3,2i6,/, &
             '    writing to ',a23)

      open(unit=25,file=outfile)
      write(25,4) legend1x_position, legend1y_position, legend2x_pixels, legend2y_pixels
4     format('legend1x_UL=',f8.3,  '   legend1y_UL=',f7.3,/, &
             'legend2x_UL=',i3,    '   legend2y_UL=',i3)
      close(25)

      write(6,*)trim(adjustl(progname))," ended normally."

      stop

      !error trap if there is no contour file
250   write(6,*) 'error opening ',cfile1
      goto 350

3001  write(6,*) 'error reading map_range.txt'
      stop 1

3010  write(6,*) 'error reading lat and lon from contour file 1'
      write(6,*)inputline
      stop 1

3015  write(6,*) 'error reading lat and lon from contour file 2'
      write(6,*)inputline
      stop 1

3020  write(6,*) 'error reading lat and lon from contour file 3'
      write(6,*)inputline
      stop 1

      end program legend_placer_dp

!******************************************************************************

      function lat_to_pixels(ytop,map_height,latmin,latmax,latnow)

      !function that calculates the y coordinate on the page in pixels from the top of the page
      !ytop: the # of pixels from the top of the map from the top of the page
      !map_height: the height of the map area on the page in cm
      !latmin:     the latitude at the base of the map
      !latmax:     The latitude at the top of the map
      !latnow      The latitude whose y position you want to convert

      implicit none
      real(kind=8) :: ytop, map_height, latmin, latmax, latnow
      real(kind=8) :: lat_to_pixels, latmax_rad, latmin_rad, latnow_rad
      real(kind=8) :: pi, y
      real(kind=8) :: merc_in
      real(kind=8) :: merc_bot,merc_top

      pi = 3.14159_8

      latmin_rad = latmin*pi/180.0_8
      latmax_rad = latmax*pi/180.0_8
      latnow_rad = latnow*pi/180.0_8

      merc_in  = log(tan(pi/4.0_8+latnow_rad/2.0_8))
      merc_top = log(tan(pi/4.0_8+latmax_rad/2.0_8))
      merc_bot = log(tan(pi/4.0_8+latmin_rad/2.0_8))

      ! Now calculate y coordinate using the Mercator projection
      y =  ytop + map_height * (1.0_8 - (merc_in-merc_bot)/(merc_top-merc_bot))

      lat_to_pixels = y

      return

      end function lat_to_pixels

!******************************************************************************

      function pixels_to_lat(ytop,map_height,latmin,latmax,ynow)

      !function that calculates the latitude given the y coordinate, where:
      !ytop:       The y offset between the top of the map and the top of the image
      !map_height: the height of the map area on the page in cm
      !latmin:     the latitude at the left edge of the map
      !latmax:     The latitude at the right edge of the map
      !ynow:       The y coordinate in cm from the bottom of the page

      implicit none
      real(kind=8) :: ytop, map_height, latmin, latmax, ycoord, ynow
      real(kind=8) :: latmin_rad, latmax_rad, latnow_rad, pixels_to_lat
      real(kind=8) :: term1, term2, term3
      real(kind=8) :: pi

      pi = 3.14159_8

      latmin_rad = latmin*pi/180.0_8
      latmax_rad = latmax*pi/180.0_8
      ycoord     = (ytop+map_height) - ynow         !convert to y value above base of map

      term1    = tan(pi/4.0_8+latmin_rad/2.0_8)
      term2    = tan(pi/4.0_8+latmax_rad/2.0_8)
      term3    = exp((ycoord/map_height)*log(term2/term1))

      latnow_rad = 2.0_8*(atan(term1*term3) - pi/4.0_8)

      pixels_to_lat = 180.0_8*latnow_rad/pi

      return

      end function pixels_to_lat
